services:
  nginx:
    build:
        context: nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:443"
    networks:
        - transcendence

  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    expose:
        - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - transcendence

  back:
    container_name: back
    build:
      context: back
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: always
    expose:
      - "8000"
    networks:
        - transcendence
    depends_on:
      - db


networks:
  transcendence:
    driver: bridge
