version: '3.0'

services:
  front:
    container_name: front
    build: ./front
    restart: always
    networks:
      - transcendence-net

  nginx:
    build:
        context: nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./front:/usr/share/nginx/html
    depends_on:
      - front
    networks:
        - transcendence-net

  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    expose:
        - "5432"
    ports:
      - "5432:5432"
    volumes:
      - database_volume:/var/lib/postgresql/data:Z
    networks:
      - transcendence-net

  back:
    container_name: back
    build:
      context: back
    volumes:
      - ./back/src:/srv:Z
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
      - DBASE

    restart: always
    expose:
      - "8000"
    networks:
        - transcendence-net
    depends_on:
      - db

networks:
  transcendence-net:
    name: transcendence-net
    driver: bridge

volumes:
    database_volume:
        driver: local
        driver_opts:
            type: none
            o: "bind,auto,-o volname=.,nobrowse,metadata"
            device: ./db
