services:
  front:
    container_name: front
    build: ./front
    restart: always
    volumes:
      - front-volume:/var/www

  nginx:
    build:
        context: nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - front-volume:/usr/share/nginx/
    depends_on:
      - front
    networks:
        - transcendence-net

  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    expose:
        - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - transcendence-net

  back:
    container_name: back
    build:
      context: back
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: always
    expose:
      - "8000"
    networks:
        - transcendence-net
    depends_on:
      - db

volumes:
  front-volume:
    driver: local


networks:
  transcendence-net:
    name: transcendence-net
    driver: bridge
